services:
  api:
    image: fabriciorostand/clinica_api:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/clinica_api
      spring.datasource.username: root
      spring.datasource.password: root
  db:
    image: fabriciorostand/mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: clinica_api
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql.clinica:/var/lib/mysql
volumes:
  mysql.clinica: